### ISSUE TITLE
Typescript errors after upgrading to version 0.0.29

### ISSUE THREAD

**Issue by oscarsilver** [facebook/react-strict-dom#244]
### Describe the issue

After upgrading to 0.0.29 the Typescript started giving errors for most of the styles in my project.

Example:
```
const sizeVariants = css.create({
  md: {
    fontSize: 10,
  },
  lg: {
    fontSize: 12,
  },
});

```
Gives the Typescript error:
```
The inferred type of 'sizeVariants' cannot be named without a reference to 'react-strict-dom/node_modules/@stylexjs/stylex/lib/StyleXTypes'. This is likely not portable. A type annotation is necessary
```

Any idea what causes this?

### Expected behavior

No type errors when creating styles

### Steps to reproduce

1. "react-strict-dom": "0.0.29"
2. "typescript": "^5.6.3",
3. "@stylexjs/eslint-plugin": "^0.9.3",

**Comment by nmn** [comment]
Could you share a small repro project?

**Comment by javascripter** [comment]
I encountered the same error at some point but I no longer can reproduce on my side.

This usually happens when:
- there are some dependency mismatches between direct dependencies (stylex) or monorepo issues
- exporting a function where the inferred return type cannot be typed explicitly in another file.

If I encounter a similar error again I'll provide more info!

**Comment by efoken** [comment]
This usually happens when you have two different versions of a package installed (stylex in this case). Look at the path in the TS error message `react-strict-dom/node_modules/@stylexjs/stylex`, there is another node_modules folder inside your installed react-strict-dom package.

You should update your installed stylex version. You can also use npm overrides or Yarn package resolutions to prevent this issue in the future.

**Comment by necolas** [comment]
Thanks for the explanation. You don't need to install stylex anymore when using RSD. See the installation instructions on the website for more information
